name: workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: mvn install

      - name: Upload AutoReferee.jar
        uses: actions/upload-artifact@v2
        with:
          name: AutoReferee.jar
          path: target/AutoReferee.jar

      - name: Upload server.properties
        uses: actions/upload-artifact@v2
        with:
          name: server.properties
          path: server/server.properties

      - name: Upload bukkit.yml
        uses: actions/upload-artifact@v2
        with:
          name: bukkit.yml
          path: server/bukkit.yml

      - name: Upload spigot.yml
        uses: actions/upload-artifact@v2
        with:
          name: spigot.yml
          path: server/spigot.yml

      - name: Upload paper.yml
        uses: actions/upload-artifact@v2
        with:
          name: paper.yml
          path: server/paper.yml
